# k8s/configmap.yml

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: __NAMESPACE__
data:
  log_level: "info"
  node_env: "__NAMESPACE__"
  app_name: "__APP_NAME__"
  metrics_enabled: "true"
