# k8s/service.yml

apiVersion: v1
kind: Service
metadata:
  name: __APP_NAME__
  namespace: __NAMESPACE__
  labels:
    app: __APP_NAME__

spec:
  type: ClusterIP # Best for internal apps behind an Ingress
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: __APP_NAME__
  sessionAffinity: None
  